from pathlib import Path

index_path = Path('index.html')
text = index_path.read_text()

old_quick = '''                    <div id="hub-watchlist" class="hidden mt-2 items-center gap-2 px-1 text-xs">\n                        <span class="shrink-0 font-medium text-gray-400">Watchlist:</span>\n                        <div id="hub-watchlist-items" class="flex min-w-0 flex-wrap gap-1.5"></div>\n                    </div>\n                    <p id="launcher-error" class="hidden mt-2 px-1 text-xs font-semibold text-red-600">Enter a valid ticker symbol.</p>'''
new_quick = '''                    <div id="hub-watchlist" class="hidden mt-2 items-center gap-2 px-1 text-xs">\n                        <span class="shrink-0 font-medium text-gray-400">Watchlist:</span>\n                        <div id="hub-watchlist-items" class="flex min-w-0 flex-wrap gap-1.5"></div>\n                    </div>\n                    <div id="hub-continue" class="hidden mt-2 items-center gap-2 px-1 text-xs">\n                        <span class="shrink-0 font-medium text-gray-400">Continue:</span>\n                        <a id="hub-continue-link" href="#" class="inline-flex min-w-0 items-center gap-1.5 rounded-full border border-blue-100 bg-blue-50 px-2.5 py-1 font-bold text-blue-700 transition hover:border-blue-200 hover:bg-blue-100">\n                            <span id="hub-continue-label" class="truncate"></span>\n                            <span aria-hidden="true">→</span>\n                        </a>\n                    </div>\n                    <p id="launcher-error" class="hidden mt-2 px-1 text-xs font-semibold text-red-600">Enter a valid ticker symbol.</p>'''
if text.count(old_quick) != 1:
    raise SystemExit(f'Quick Launch footer expected once, found {text.count(old_quick)}')
text = text.replace(old_quick, new_quick, 1)

old_js = '''    renderHubWatchlist();\n    window.addEventListener('storage', event => {\n        if (event.key === 'sethiWatchlist') renderHubWatchlist();\n    });\n\n    const form = document.getElementById('idea-form');'''
new_js = '''    renderHubWatchlist();\n    window.addEventListener('storage', event => {\n        if (event.key === 'sethiWatchlist') renderHubWatchlist();\n    });\n\n    const hubContinue = document.getElementById('hub-continue');\n    const hubContinueLink = document.getElementById('hub-continue-link');\n    const hubContinueLabel = document.getElementById('hub-continue-label');\n\n    function getLastSethiwayDestination() {\n        try {\n            const saved = JSON.parse(localStorage.getItem('sethiwayLastDestination') || 'null');\n            if (!saved || typeof saved !== 'object') return null;\n            const href = String(saved.href || '');\n            const label = String(saved.label || '');\n            const updatedAt = Number(saved.updatedAt || 0);\n            const allowedHref = /^(sethimacro|sethistock|sethiportfolio|sethiquant)\\.html(?:\\?[^#]*)?(?:#.*)?$/i.test(href);\n            const recentEnough = updatedAt > 0 && Date.now() - updatedAt < 1000 * 60 * 60 * 24 * 30;\n            if (!allowedHref || !label || !recentEnough) return null;\n            return { href, label };\n        } catch {\n            return null;\n        }\n    }\n\n    function renderHubContinue() {\n        const destination = getLastSethiwayDestination();\n        if (!destination) {\n            hubContinue.classList.add('hidden');\n            hubContinue.classList.remove('flex');\n            return;\n        }\n        hubContinueLink.href = destination.href;\n        hubContinueLabel.textContent = destination.label;\n        hubContinue.classList.remove('hidden');\n        hubContinue.classList.add('flex');\n    }\n\n    renderHubContinue();\n    window.addEventListener('storage', event => {\n        if (event.key === 'sethiwayLastDestination') renderHubContinue();\n    });\n\n    const form = document.getElementById('idea-form');'''
if text.count(old_js) != 1:
    raise SystemExit(f'Watchlist JS anchor expected once, found {text.count(old_js)}')
text = text.replace(old_js, new_js, 1)

old_recent = '''                <div class="grid grid-cols-1 md:grid-cols-3 gap-4">\n                    <a href="#top" class="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:border-blue-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-gray-400">Hub</span>\n                            <span class="text-blue-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Watchlist Shortcuts</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Saved SethiStock tickers now appear inside Quick Launch for one-click access.</p>\n                    </a>\n\n                    <a href="#top" class="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:border-blue-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-gray-400">Hub</span>\n                            <span class="text-blue-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Quick Launch</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Enter a ticker on the homepage and open it directly in SethiStock.</p>\n                    </a>\n\n                    <a href="sethiportfolio.html#portfolio-lab" class="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:border-amber-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-amber-600">SethiPortfolio</span>\n                            <span class="text-amber-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Portfolio Lab</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Review exposure, FX effects, portfolio risk and proposed reallocations in one place.</p>\n                    </a>\n                </div>'''
new_recent = '''                <div class="grid grid-cols-1 md:grid-cols-3 gap-4">\n                    <a href="#top" class="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:border-blue-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-gray-400">Hub</span>\n                            <span class="text-blue-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Continue Shortcut</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Return to the last SethiWay tool, stock or section you were using.</p>\n                    </a>\n\n                    <a href="#top" class="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:border-blue-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-gray-400">Hub</span>\n                            <span class="text-blue-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Watchlist Shortcuts</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Saved SethiStock tickers now appear inside Quick Launch for one-click access.</p>\n                    </a>\n\n                    <a href="#top" class="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:border-blue-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-gray-400">Hub</span>\n                            <span class="text-blue-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Quick Launch</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Enter a ticker on the homepage and open it directly in SethiStock.</p>\n                    </a>\n                </div>'''
if text.count(old_recent) != 1:
    raise SystemExit(f'Recently Added grid expected once, found {text.count(old_recent)}')
text = text.replace(old_recent, new_recent, 1)

for item in ['id="hub-continue"', 'id="hub-continue-link"', 'function renderHubContinue()', '>Continue Shortcut</h3>']:
    if text.count(item) != 1:
        raise SystemExit(f'Missing or duplicated hub continue item: {item}')
if '—' in text:
    raise SystemExit('Em dash remains in homepage copy')
index_path.write_text(text)

history_js = '''(() => {\n    const STORAGE_KEY = 'sethiwayLastDestination';\n    const page = window.location.pathname.split('/').pop() || '';\n    const toolNames = {\n        'sethimacro.html': 'SethiMacro',\n        'sethistock.html': 'SethiStock',\n        'sethiportfolio.html': 'SethiPortfolio',\n        'sethiquant.html': 'SethiQuant'\n    };\n    const tool = toolNames[page];\n    if (!tool) return;\n\n    const knownSections = {\n        'job-market': 'Job Market',\n        'inflation-rates': 'Inflation & Rates',\n        'currencies': 'Currencies',\n        'key-metrics': 'Key Metrics',\n        'research-labs': 'Research Labs',\n        'valuation': 'Valuations',\n        'comparisons': 'Comparisons',\n        'extra': 'Extra',\n        'portfolio-lab': 'Portfolio Lab',\n        'decisions': 'Decisions',\n        'exposure': 'Exposure Map',\n        'fx': 'FX Analytics',\n        'risk': 'Portfolio Risk',\n        'section-options': 'Options & Greeks',\n        'section-backtest': 'Backtesting',\n        'section-var': 'Market Risk Lab'\n    };\n\n    function fallbackSection(hash) {\n        const clean = hash.replace(/^#/, '').replace(/^section-/, '').replace(/-/g, ' ').trim();\n        return clean ? clean.replace(/\\b\\w/g, char => char.toUpperCase()) : '';\n    }\n\n    function currentLabel() {\n        const details = [];\n        const params = new URLSearchParams(window.location.search);\n        if (page === 'sethistock.html') {\n            const ticker = (params.get('ticker') || '').trim().toUpperCase();\n            if (/^[A-Z0-9.^-]{1,20}$/.test(ticker)) details.push(ticker);\n        }\n        const hashKey = window.location.hash.replace(/^#/, '');\n        if (hashKey) details.push(knownSections[hashKey] || fallbackSection(window.location.hash));\n        return details.length ? `${tool} · ${details.join(' · ')}` : tool;\n    }\n\n    function saveDestination() {\n        try {\n            localStorage.setItem(STORAGE_KEY, JSON.stringify({\n                href: `${page}${window.location.search}${window.location.hash}`,\n                label: currentLabel(),\n                updatedAt: Date.now()\n            }));\n        } catch {}\n    }\n\n    saveDestination();\n    window.addEventListener('hashchange', saveDestination);\n    window.addEventListener('popstate', saveDestination);\n})();\n'''
Path('sethiway-history.js').write_text(history_js)

for filename in ['sethimacro.html', 'sethistock.html', 'sethiportfolio.html', 'sethiquant.html']:
    path = Path(filename)
    page_text = path.read_text()
    tag = '<script src="sethiway-history.js"></script>'
    if tag in page_text:
        continue
    if page_text.count('</body>') != 1:
        raise SystemExit(f'{filename}: expected one closing body tag, found {page_text.count("</body>")}')
    page_text = page_text.replace('</body>', f'    {tag}\n</body>', 1)
    path.write_text(page_text)
