from pathlib import Path

path = Path('index.html')
text = path.read_text()

old_quick = '''                    <div class="mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 px-1 text-xs font-bold text-gray-500">\n                        <span class="font-medium text-gray-400">Go straight to:</span>\n                        <a href="sethimacro.html" class="hover:text-red-500 transition">SethiMacro</a>\n                        <a href="sethiportfolio.html" class="hover:text-amber-500 transition">SethiPortfolio</a>\n                        <a href="sethiquant.html" class="hover:text-blue-500 transition">SethiQuant</a>\n                    </div>\n                    <p id="launcher-error" class="hidden mt-2 px-1 text-xs font-semibold text-red-600">Enter a valid ticker symbol.</p>'''
new_quick = '''                    <div class="mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 px-1 text-xs font-bold text-gray-500">\n                        <span class="font-medium text-gray-400">Go straight to:</span>\n                        <a href="sethimacro.html" class="hover:text-red-500 transition">SethiMacro</a>\n                        <a href="sethiportfolio.html" class="hover:text-amber-500 transition">SethiPortfolio</a>\n                        <a href="sethiquant.html" class="hover:text-blue-500 transition">SethiQuant</a>\n                    </div>\n                    <div id="hub-watchlist" class="hidden mt-2 items-center gap-2 px-1 text-xs">\n                        <span class="shrink-0 font-medium text-gray-400">Watchlist:</span>\n                        <div id="hub-watchlist-items" class="flex min-w-0 flex-wrap gap-1.5"></div>\n                    </div>\n                    <p id="launcher-error" class="hidden mt-2 px-1 text-xs font-semibold text-red-600">Enter a valid ticker symbol.</p>'''
if text.count(old_quick) != 1:
    raise SystemExit(f'Quick Launch anchor expected once, found {text.count(old_quick)}')
text = text.replace(old_quick, new_quick, 1)

old_js = '''    launcherTicker.addEventListener('input', () => launcherError.classList.add('hidden'));\n\n    const form = document.getElementById('idea-form');'''
new_js = '''    launcherTicker.addEventListener('input', () => launcherError.classList.add('hidden'));\n\n    const hubWatchlist = document.getElementById('hub-watchlist');\n    const hubWatchlistItems = document.getElementById('hub-watchlist-items');\n\n    function getHubWatchlist() {\n        try {\n            const saved = JSON.parse(localStorage.getItem('sethiWatchlist') || '[]');\n            if (!Array.isArray(saved)) return [];\n            return [...new Set(saved\n                .map(ticker => String(ticker || '').trim().toUpperCase())\n                .filter(ticker => /^[A-Z0-9.^-]{1,20}$/.test(ticker))\n            )].slice(0, 6);\n        } catch {\n            return [];\n        }\n    }\n\n    function renderHubWatchlist() {\n        const tickers = getHubWatchlist();\n        hubWatchlistItems.replaceChildren();\n        if (!tickers.length) {\n            hubWatchlist.classList.add('hidden');\n            hubWatchlist.classList.remove('flex');\n            return;\n        }\n\n        tickers.forEach(ticker => {\n            const link = document.createElement('a');\n            link.href = `sethistock.html?ticker=${encodeURIComponent(ticker)}&source=hub-watchlist`;\n            link.textContent = ticker;\n            link.className = 'rounded-full border border-gray-200 bg-gray-50 px-2.5 py-1 font-bold text-gray-600 transition hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700';\n            hubWatchlistItems.appendChild(link);\n        });\n\n        hubWatchlist.classList.remove('hidden');\n        hubWatchlist.classList.add('flex');\n    }\n\n    renderHubWatchlist();\n    window.addEventListener('storage', event => {\n        if (event.key === 'sethiWatchlist') renderHubWatchlist();\n    });\n\n    const form = document.getElementById('idea-form');'''
if text.count(old_js) != 1:
    raise SystemExit(f'Launcher JS anchor expected once, found {text.count(old_js)}')
text = text.replace(old_js, new_js, 1)

old_recent = '''                <div class="grid grid-cols-1 md:grid-cols-3 gap-4">\n                    <a href="#top" class="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:border-blue-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-gray-400">Hub</span>\n                            <span class="text-blue-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Quick Launch</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Enter a ticker on the homepage and open it directly in SethiStock.</p>\n                    </a>\n\n                    <a href="sethiportfolio.html#portfolio-lab" class="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:border-amber-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-amber-600">SethiPortfolio</span>\n                            <span class="text-amber-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Portfolio Lab</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Review exposure, FX effects, portfolio risk and proposed reallocations in one place.</p>\n                    </a>\n\n                    <a href="sethiquant.html#section-var" class="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:border-blue-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-blue-600">SethiQuant</span>\n                            <span class="text-blue-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Market Risk Lab</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Run VaR, correlation, stress tests and risk contribution analysis on a portfolio.</p>\n                    </a>\n                </div>'''
new_recent = '''                <div class="grid grid-cols-1 md:grid-cols-3 gap-4">\n                    <a href="#top" class="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:border-blue-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-gray-400">Hub</span>\n                            <span class="text-blue-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Watchlist Shortcuts</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Saved SethiStock tickers now appear inside Quick Launch for one-click access.</p>\n                    </a>\n\n                    <a href="#top" class="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:border-blue-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-gray-400">Hub</span>\n                            <span class="text-blue-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Quick Launch</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Enter a ticker on the homepage and open it directly in SethiStock.</p>\n                    </a>\n\n                    <a href="sethiportfolio.html#portfolio-lab" class="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:border-amber-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-amber-600">SethiPortfolio</span>\n                            <span class="text-amber-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Portfolio Lab</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Review exposure, FX effects, portfolio risk and proposed reallocations in one place.</p>\n                    </a>\n                </div>'''
if text.count(old_recent) != 1:
    raise SystemExit(f'Recently Added grid expected once, found {text.count(old_recent)}')
text = text.replace(old_recent, new_recent, 1)

for item in ['id="hub-watchlist"', 'id="hub-watchlist-items"', 'function renderHubWatchlist()', '>Watchlist Shortcuts</h3>']:
    if text.count(item) != 1:
        raise SystemExit(f'Missing or duplicated item: {item}')
if '—' in text:
    raise SystemExit('Em dash remains in homepage copy')

path.write_text(text)
