from pathlib import Path

path = Path('index.html')
text = path.read_text()

old_heading = '''                <div class="mb-4">\n                    <p class="text-[10px] font-black uppercase tracking-[0.18em] text-blue-600">The Platform</p>\n                    <h2 class="text-2xl md:text-3xl font-black mt-1">Four tools. One connected workflow.</h2>\n                </div>'''
new_heading = '''                <div class="mb-5 flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between">\n                    <div>\n                        <p class="text-[10px] font-black uppercase tracking-[0.18em] text-blue-600">The Platform</p>\n                        <h2 class="text-2xl md:text-3xl font-black mt-1">Four tools. One connected workflow.</h2>\n                    </div>\n                    <div id="platform-snapshot" class="grid grid-cols-2 overflow-hidden rounded-xl border border-gray-200 bg-gray-200 shadow-sm sm:grid-cols-4 xl:min-w-[560px]" aria-label="Platform snapshot">\n                        <div class="bg-white px-4 py-3">\n                            <div id="snapshot-tools" class="text-xl font-black text-gray-950">4</div>\n                            <div class="mt-0.5 text-[10px] font-bold uppercase tracking-wider text-gray-400">Live tools</div>\n                        </div>\n                        <div class="bg-white px-4 py-3">\n                            <div id="snapshot-routes" class="text-xl font-black text-blue-600">0</div>\n                            <div class="mt-0.5 text-[10px] font-bold uppercase tracking-wider text-gray-400">Search routes</div>\n                        </div>\n                        <div class="bg-white px-4 py-3">\n                            <div id="snapshot-watchlist" class="text-xl font-black text-emerald-600">0</div>\n                            <div class="mt-0.5 text-[10px] font-bold uppercase tracking-wider text-gray-400">Saved tickers</div>\n                        </div>\n                        <div class="bg-white px-4 py-3">\n                            <div id="snapshot-updates" class="text-xl font-black text-amber-500">0</div>\n                            <div class="mt-0.5 text-[10px] font-bold uppercase tracking-wider text-gray-400">Recent changes</div>\n                        </div>\n                    </div>\n                </div>'''
if text.count(old_heading) != 1:
    raise SystemExit(f'Platform heading expected once, found {text.count(old_heading)}')
text = text.replace(old_heading, new_heading, 1)

old_grid_open = '<div class="grid grid-cols-1 md:grid-cols-3 gap-4">'
if text.count(old_grid_open) != 1:
    raise SystemExit(f'Recent grid expected once, found {text.count(old_grid_open)}')
text = text.replace(old_grid_open, '<div id="recent-updates-grid" class="grid grid-cols-1 md:grid-cols-3 gap-4">', 1)

old_recent = '''                    <button type="button" onclick="openCommandPalette()" class="group rounded-2xl border border-gray-200 bg-white p-5 text-left shadow-sm hover:border-blue-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-gray-400">Hub</span>\n                            <span class="text-blue-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Command Palette</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Use Ctrl or Cmd + K to jump to a tool, section or ticker.</p>\n                    </button>\n\n                    <a href="#top" class="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:border-blue-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-gray-400">Hub</span>\n                            <span class="text-blue-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Continue Shortcut</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Return to the last SethiWay tool, stock or section you were using.</p>\n                    </a>\n\n                    <a href="#top" class="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:border-blue-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-gray-400">Hub</span>\n                            <span class="text-blue-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Watchlist Shortcuts</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Saved SethiStock tickers now appear inside Quick Launch for one-click access.</p>\n                    </a>'''
new_recent = '''                    <a href="#platform" class="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:border-blue-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-gray-400">Hub</span>\n                            <span class="text-blue-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Platform Snapshot</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">See live tool, search route, watchlist and recent-update counts at a glance.</p>\n                    </a>\n\n                    <button type="button" onclick="openCommandPalette()" class="group rounded-2xl border border-gray-200 bg-white p-5 text-left shadow-sm hover:border-blue-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-gray-400">Hub</span>\n                            <span class="text-blue-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Command Palette</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Use Ctrl or Cmd + K to jump to a tool, section or ticker.</p>\n                    </button>\n\n                    <a href="#top" class="group rounded-2xl border border-gray-200 bg-white p-5 shadow-sm hover:border-blue-200 hover:shadow-md transition">\n                        <div class="flex items-center justify-between gap-3">\n                            <span class="text-[10px] font-black uppercase tracking-[0.16em] text-gray-400">Hub</span>\n                            <span class="text-blue-600 group-hover:translate-x-0.5 transition-transform">→</span>\n                        </div>\n                        <h3 class="mt-3 text-lg font-black text-gray-950">Continue Shortcut</h3>\n                        <p class="mt-2 text-sm leading-relaxed text-gray-500">Return to the last SethiWay tool, stock or section you were using.</p>\n                    </a>'''
if text.count(old_recent) != 1:
    raise SystemExit(f'Recent cards block expected once, found {text.count(old_recent)}')
text = text.replace(old_recent, new_recent, 1)

old_watchlist = '''    function getHubWatchlist() {\n        try {\n            const saved = JSON.parse(localStorage.getItem('sethiWatchlist') || '[]');\n            if (!Array.isArray(saved)) return [];\n            return [...new Set(saved\n                .map(ticker => String(ticker || '').trim().toUpperCase())\n                .filter(ticker => /^[A-Z0-9.^-]{1,20}$/.test(ticker))\n            )].slice(0, 6);\n        } catch {\n            return [];\n        }\n    }'''
new_watchlist = '''    function getHubWatchlistAll() {\n        try {\n            const saved = JSON.parse(localStorage.getItem('sethiWatchlist') || '[]');\n            if (!Array.isArray(saved)) return [];\n            return [...new Set(saved\n                .map(ticker => String(ticker || '').trim().toUpperCase())\n                .filter(ticker => /^[A-Z0-9.^-]{1,20}$/.test(ticker))\n            )];\n        } catch {\n            return [];\n        }\n    }\n\n    function getHubWatchlist() {\n        return getHubWatchlistAll().slice(0, 6);\n    }'''
if text.count(old_watchlist) != 1:
    raise SystemExit(f'Watchlist helper expected once, found {text.count(old_watchlist)}')
text = text.replace(old_watchlist, new_watchlist, 1)

old_storage = '''    renderHubWatchlist();\n    window.addEventListener('storage', event => {\n        if (event.key === 'sethiWatchlist') renderHubWatchlist();\n    });'''
new_storage = '''    renderHubWatchlist();\n    window.addEventListener('storage', event => {\n        if (event.key === 'sethiWatchlist') {\n            renderHubWatchlist();\n            renderPlatformSnapshot();\n        }\n    });'''
if text.count(old_storage) != 1:
    raise SystemExit(f'Watchlist storage listener expected once, found {text.count(old_storage)}')
text = text.replace(old_storage, new_storage, 1)

anchor = '''    renderHubContinue();\n    window.addEventListener('storage', event => {\n        if (event.key === 'sethiwayLastDestination') renderHubContinue();\n    });\n\n    const form = document.getElementById('idea-form');'''
replacement = '''    renderHubContinue();\n    window.addEventListener('storage', event => {\n        if (event.key === 'sethiwayLastDestination') renderHubContinue();\n    });\n\n    function renderPlatformSnapshot() {\n        const tools = document.querySelectorAll('#workflow article').length;\n        const routes = platformCommands.length;\n        const watchlist = getHubWatchlistAll().length;\n        const updates = document.getElementById('recent-updates-grid')?.children.length || 0;\n        document.getElementById('snapshot-tools').textContent = String(tools);\n        document.getElementById('snapshot-routes').textContent = String(routes);\n        document.getElementById('snapshot-watchlist').textContent = String(watchlist);\n        document.getElementById('snapshot-updates').textContent = String(updates);\n    }\n\n    renderPlatformSnapshot();\n\n    const form = document.getElementById('idea-form');'''
if text.count(anchor) != 1:
    raise SystemExit(f'Continue anchor expected once, found {text.count(anchor)}')
text = text.replace(anchor, replacement, 1)

for token in ['id="platform-snapshot"', 'id="snapshot-routes"', 'id="recent-updates-grid"', 'function renderPlatformSnapshot()', '>Platform Snapshot</h3>']:
    if text.count(token) != 1:
        raise SystemExit(f'Missing or duplicated token: {token}')
if '—' in text:
    raise SystemExit('Em dash remains in homepage copy')

path.write_text(text)
