from pathlib import Path

p = Path('index.html')
s = p.read_text()

anchor = '''                <p class="mt-3 text-base md:text-lg text-gray-500 max-w-3xl mx-auto leading-relaxed">\n                    Macro context, security analysis, portfolio management and quantitative risk. Each tool is built around real financial decisions.\n                </p>\n                <div class="mt-6 max-w-2xl mx-auto rounded-2xl border border-gray-200 bg-white p-3 shadow-sm text-left">'''

replacement = '''                <p class="mt-3 text-base md:text-lg text-gray-500 max-w-3xl mx-auto leading-relaxed">\n                    Macro context, security analysis, portfolio management and quantitative risk. Each tool is built around real financial decisions.\n                </p>\n\n                <div id="first-visit-guide" class="hidden mt-5 max-w-2xl mx-auto rounded-2xl border border-blue-100 bg-blue-50/60 p-3 shadow-sm text-left">\n                    <div class="flex items-start justify-between gap-4 px-1">\n                        <div>\n                            <p class="text-[10px] font-black uppercase tracking-[0.18em] text-blue-600">First time here?</p>\n                            <h2 class="mt-1 text-base font-black text-gray-950">What do you want to do?</h2>\n                        </div>\n                        <button id="first-visit-dismiss" type="button" class="shrink-0 rounded-lg px-2.5 py-1.5 text-xs font-bold text-gray-400 transition hover:bg-white hover:text-gray-700">Skip</button>\n                    </div>\n                    <div class="mt-3 grid grid-cols-1 gap-2 sm:grid-cols-3">\n                        <button type="button" data-guide-action="stock" class="rounded-xl border border-gray-200 bg-white px-3 py-3 text-left transition hover:border-emerald-200 hover:bg-emerald-50">\n                            <span class="block text-sm font-black text-gray-900">Research a company</span>\n                            <span class="mt-1 block text-xs leading-relaxed text-gray-500">Start with a company or ticker.</span>\n                        </button>\n                        <button type="button" data-guide-action="macro" class="rounded-xl border border-gray-200 bg-white px-3 py-3 text-left transition hover:border-red-200 hover:bg-red-50">\n                            <span class="block text-sm font-black text-gray-900">Understand the market</span>\n                            <span class="mt-1 block text-xs leading-relaxed text-gray-500">Open the macro dashboard.</span>\n                        </button>\n                        <button type="button" data-guide-action="risk" class="rounded-xl border border-gray-200 bg-white px-3 py-3 text-left transition hover:border-blue-200 hover:bg-blue-50">\n                            <span class="block text-sm font-black text-gray-900">Analyse portfolio risk</span>\n                            <span class="mt-1 block text-xs leading-relaxed text-gray-500">Open Market Risk Lab.</span>\n                        </button>\n                    </div>\n                </div>\n\n                <div class="mt-6 max-w-2xl mx-auto rounded-2xl border border-gray-200 bg-white p-3 shadow-sm text-left">'''

assert anchor in s, 'Hero anchor not found'
s = s.replace(anchor, replacement, 1)

js_anchor = "    const adminModal = document.getElementById('login-modal');\n"
js_block = '''    const firstVisitGuide = document.getElementById('first-visit-guide');\n    const firstVisitDismiss = document.getElementById('first-visit-dismiss');\n    const firstVisitSeenKey = 'sethiwayFirstVisitGuideSeen';\n\n    function markFirstVisitGuideSeen() {\n        try { localStorage.setItem(firstVisitSeenKey, '1'); } catch {}\n    }\n\n    function hideFirstVisitGuide() {\n        firstVisitGuide.classList.add('hidden');\n    }\n\n    function shouldShowFirstVisitGuide() {\n        if (new URLSearchParams(window.location.search).get('guide') === '1') return true;\n        try { return localStorage.getItem(firstVisitSeenKey) !== '1'; } catch { return true; }\n    }\n\n    if (shouldShowFirstVisitGuide()) firstVisitGuide.classList.remove('hidden');\n\n    firstVisitDismiss.addEventListener('click', () => {\n        markFirstVisitGuideSeen();\n        hideFirstVisitGuide();\n    });\n\n    firstVisitGuide.querySelectorAll('[data-guide-action]').forEach(button => {\n        button.addEventListener('click', () => {\n            const action = button.dataset.guideAction;\n            markFirstVisitGuideSeen();\n            if (action === 'stock') {\n                hideFirstVisitGuide();\n                const tickerInput = document.getElementById('launcher-ticker');\n                tickerInput.focus();\n                tickerInput.scrollIntoView({ behavior: 'smooth', block: 'center' });\n                return;\n            }\n            if (action === 'macro') window.location.href = 'sethimacro.html';\n            if (action === 'risk') window.location.href = 'sethiquant.html#section-var';\n        });\n    });\n\n'''

assert js_anchor in s, 'JS anchor not found'
s = s.replace(js_anchor, js_block + js_anchor, 1)

assert s.count('id="first-visit-guide"') == 1
assert s.count('data-guide-action=') == 3
assert '—' not in s
p.write_text(s)
