from pathlib import Path

p = Path('sethistock.html')
s = p.read_text()

old_style = '''        html { scroll-behavior: smooth; }\n        .tf-btn.active, .type-btn.active { background-color: #2563eb; color: white; border-color: #2563eb; }\n        .modal-active { overflow: hidden; }'''
new_style = '''        html { scroll-behavior: smooth; scroll-padding-top: 8rem; }\n        #dashboard, #key-metrics, #comparisons, #research-labs, #valuation, #extra { scroll-margin-top: 8rem; }\n        .tf-btn.active, .type-btn.active { background-color: #2563eb; color: white; border-color: #2563eb; }\n        .modal-active { overflow: hidden; }\n        @media (prefers-reduced-motion: reduce) { html { scroll-behavior: auto; } }'''
assert old_style in s
s = s.replace(old_style, new_style, 1)

old_nav = '''    <nav class="flex justify-between items-center py-6 px-6 md:px-10 bg-white shadow-sm sticky top-0 z-50">\n        <a href="index.html" class="flex items-center"><img src="logo.png" alt="Sethiway Logo" class="h-10 w-auto invert"></a>\n        <div class="hidden md:flex items-center space-x-6 text-xs font-bold uppercase tracking-widest text-gray-500">\n            <button onclick="window.scrollTo({ top: 0, behavior: 'smooth' });" class="hover:text-blue-600 transition cursor-pointer uppercase tracking-widest font-bold">Current Stats</button>\n            <a href="#key-metrics" class="hover:text-blue-600 transition">Key Graphs</a>\n            <a href="#comparisons" class="hover:text-blue-600 transition">Comparisons</a>\n            <a href="#research-labs" class="hover:text-blue-600 transition">Research</a>\n            <a href="#valuation" class="hover:text-blue-600 transition">Valuations</a>\n            <a href="#extra" class="hover:text-blue-600 transition">Extra</a>\n            <a href="index.html" class="hover:text-blue-600 transition ml-4 pl-4 border-l border-gray-300">Back to Hub</a>\n        </div>\n    </nav>'''
new_nav = '''    <!-- SETHIWAY UNIFIED NAVIGATION -->\n    <nav class="sticky top-0 z-50 bg-white/95 backdrop-blur-md border-b border-gray-200" aria-label="SethiStock navigation">\n        <div class="max-w-[1600px] mx-auto px-5 md:px-8">\n            <div class="relative flex items-center gap-4 min-w-0">\n                <a href="index.html" class="flex items-center py-3 shrink-0" aria-label="SethiWay home">\n                    <img src="logo.png" alt="SethiWay" class="h-6 sm:h-10 w-auto invert">\n                </a>\n                <div class="hidden xl:flex absolute left-1/2 -translate-x-1/2 items-center justify-center gap-6 whitespace-nowrap text-sm font-bold text-gray-600">\n                    <button type="button" onclick="window.scrollTo({ top: 0, behavior: 'smooth' });" class="hover:text-blue-600 transition">Overview</button>\n                    <a href="#key-metrics" class="hover:text-blue-600 transition">Financials</a>\n                    <a href="#comparisons" class="hover:text-blue-600 transition">Comparisons</a>\n                    <a href="#research-labs" class="hover:text-blue-600 transition">Research</a>\n                    <a href="#valuation" class="hover:text-blue-600 transition">Valuation</a>\n                    <a href="#extra" class="hover:text-blue-600 transition">More</a>\n                </div>\n                <div class="flex items-center gap-2 shrink-0 ml-auto">\n                    <button type="button" onclick="window.scrollTo({ top: 0, behavior: 'smooth' }); setTimeout(() => document.getElementById('ticker-input').focus(), 300);" class="hidden sm:inline-flex px-3 py-2.5 border border-gray-200 bg-white text-gray-700 text-xs xl:text-sm font-bold rounded-lg hover:border-blue-300 hover:text-blue-700 hover:bg-blue-50 transition shadow-sm whitespace-nowrap">New Search</button>\n                    <a href="index.html" class="px-3 xl:px-4 py-2.5 bg-gray-900 text-white text-xs xl:text-sm font-bold rounded-lg hover:bg-gray-800 transition shadow-sm whitespace-nowrap">Back to Hub</a>\n                </div>\n            </div>\n            <div class="xl:hidden flex items-center justify-center gap-5 overflow-x-auto whitespace-nowrap text-xs font-black text-gray-600 pb-3">\n                <button type="button" onclick="window.scrollTo({ top: 0, behavior: 'smooth' });" class="hover:text-blue-600 transition">Overview</button>\n                <a href="#key-metrics" class="hover:text-blue-600 transition">Financials</a>\n                <a href="#comparisons" class="hover:text-blue-600 transition">Comparisons</a>\n                <a href="#research-labs" class="hover:text-blue-600 transition">Research</a>\n                <a href="#valuation" class="hover:text-blue-600 transition">Valuation</a>\n                <a href="#extra" class="hover:text-blue-600 transition">More</a>\n            </div>\n        </div>\n    </nav>'''
assert old_nav in s
s = s.replace(old_nav, new_nav, 1)

old_progress = '''    <!-- THIN BLUE PROGRESS BAR -->\n    <div id="progress-container" class="w-full h-1 bg-transparent overflow-hidden sticky top-[88px] z-40 transition-opacity duration-500 opacity-0">\n        <div id="progress-bar" class="h-full bg-blue-600 w-0 transition-all duration-300 ease-out shadow-[0_0_10px_rgba(37,99,235,0.8)]"></div>\n    </div>'''
new_progress = '''    <!-- ANALYSIS PROGRESS -->\n    <div id="progress-container" class="w-full h-[3px] bg-blue-50 overflow-hidden transition-opacity duration-500 opacity-0" aria-label="Loading SethiStock analysis">\n        <div id="progress-bar" class="h-full bg-blue-600 w-0 transition-all duration-300 ease-out"></div>\n    </div>'''
assert old_progress in s
s = s.replace(old_progress, new_progress, 1)

old_watchlist = '''    <div class="bg-white border-b border-gray-200 px-6 py-3 w-full overflow-x-auto whitespace-nowrap hidden md:flex items-center space-x-4" id="watchlist-ribbon">\n        <span class="text-xs font-bold text-gray-400 uppercase tracking-widest">My Watchlist:</span>\n        <div id="watchlist-container" class="flex space-x-2"></div>\n    </div>\n\n'''
assert old_watchlist in s
s = s.replace(old_watchlist, '', 1)

old_header = '''    <header class="pt-12 pb-8 flex flex-col justify-center items-center text-center px-6">\n        <h1 class="text-4xl md:text-5xl font-black tracking-tight mb-4 text-gray-900">SETHISTOCK.</h1>\n        <form id="search-form" class="w-full max-w-lg flex shadow-xl rounded-lg mt-2 border border-gray-200 relative">\n            <input type="text" id="ticker-input" autocomplete="off" oninput="fetchSuggestions(this.value)" required placeholder="Enter Ticker or Company (e.g. AAPL or Apple)" class="w-full px-6 py-4 text-lg border-none focus:outline-none uppercase font-bold text-gray-700 rounded-l-lg">\n            <button type="submit" id="search-btn" class="px-8 bg-blue-600 text-white font-bold hover:bg-blue-700 transition rounded-r-lg z-10">Analyse</button>\n            \n            <ul id="search-suggestions" class="absolute top-full left-0 w-full bg-white border border-gray-200 rounded-b-xl shadow-2xl mt-1 hidden overflow-hidden text-left z-50">\n            </ul>\n        </form>'''
new_header = '''    <header class="max-w-[1600px] mx-auto pt-8 pb-7 flex flex-col justify-center items-center text-center px-5 md:px-8">\n        <h1 class="text-3xl sm:text-5xl md:text-6xl font-black tracking-tight text-gray-900">SETHI<span class="text-emerald-600">STOCK</span></h1>\n        <form id="search-form" class="w-full max-w-xl flex shadow-sm rounded-xl mt-5 border border-gray-200 bg-white relative">\n            <input type="text" id="ticker-input" autocomplete="off" oninput="fetchSuggestions(this.value)" required placeholder="Enter ticker or company, e.g. AAPL or Apple" class="w-full px-5 py-3.5 text-base border-none focus:outline-none uppercase font-bold text-gray-700 rounded-l-xl bg-transparent">\n            <button type="submit" id="search-btn" class="px-7 bg-blue-600 text-white font-bold hover:bg-blue-700 transition rounded-r-xl z-10">Analyse</button>\n            \n            <ul id="search-suggestions" class="absolute top-full left-0 w-full bg-white border border-gray-200 rounded-xl shadow-xl mt-2 hidden overflow-hidden text-left z-50">\n            </ul>\n        </form>'''
assert old_header in s
s = s.replace(old_header, new_header, 1)

watchlist_insert_anchor = '''        </form>\n        <p id="error-message" class="text-red-500 mt-4 hidden font-semibold"></p>'''
watchlist_insert = '''        </form>\n        <div id="watchlist-ribbon" class="hidden md:flex mt-4 max-w-2xl w-full items-center gap-3 overflow-x-auto whitespace-nowrap rounded-xl border border-gray-200 bg-white px-4 py-2.5 shadow-sm text-left">\n            <span class="shrink-0 text-[10px] font-black text-gray-400 uppercase tracking-widest">Watchlist</span>\n            <div id="watchlist-container" class="flex space-x-2"></div>\n        </div>\n        <p id="error-message" class="text-red-500 mt-4 hidden font-semibold"></p>'''
assert watchlist_insert_anchor in s
s = s.replace(watchlist_insert_anchor, watchlist_insert, 1)

assert s.count('aria-label="SethiStock navigation"') == 1
assert s.count('id="watchlist-ribbon"') == 1
assert 'sticky top-[88px]' not in s
assert 'SETHISTOCK.</h1>' not in s
assert '—' not in s
p.write_text(s)
