from pathlib import Path

p = Path('sethiportfolio-admin.html')
s = p.read_text(encoding='utf-8')

old = '''                            <div class="grid grid-cols-2 gap-3"><div><label class="label" for="allocation-funding-price">Price</label><input id="allocation-funding-price" type="number" min="0" step="0.0001" class="field" required></div><div><label class="label" for="allocation-funding-fees">Fees</label><input id="allocation-funding-fees" type="number" min="0" step="0.01" value="0" class="field" required></div></div>\n'''
new = '''                            <div class="grid grid-cols-2 sm:grid-cols-4 gap-3"><div><label class="label" for="allocation-funding-currency">Currency</label><input id="allocation-funding-currency" class="field" value="GBP" readonly></div><div><label class="label" for="allocation-funding-fx">FX to GBP</label><input id="allocation-funding-fx" type="number" min="0" step="0.000001" value="1" class="field"></div><div><label class="label" for="allocation-funding-price">Price</label><input id="allocation-funding-price" type="number" min="0" step="0.0001" class="field" required></div><div><label class="label" for="allocation-funding-fees">Fees</label><input id="allocation-funding-fees" type="number" min="0" step="0.01" value="0" class="field" required></div></div>\n'''
if old not in s: raise SystemExit('funding form marker missing')
s = s.replace(old, new, 1)

old = '''                                <div class="grid grid-cols-3 gap-2"><div><label class="label" for="allocation-correction-funding-qty">Quantity</label><input id="allocation-correction-funding-qty" type="number" min="0" step="0.000001" class="field" required></div><div><label class="label" for="allocation-correction-funding-price">Price</label><input id="allocation-correction-funding-price" type="number" min="0" step="0.0001" class="field" required></div><div><label class="label" for="allocation-correction-funding-fees">Fees</label><input id="allocation-correction-funding-fees" type="number" min="0" step="0.01" class="field" required></div></div>\n'''
new = '''                                <div class="grid grid-cols-2 sm:grid-cols-4 gap-2"><div><label class="label" for="allocation-correction-funding-qty">Quantity</label><input id="allocation-correction-funding-qty" type="number" min="0" step="0.000001" class="field" required></div><div><label class="label" for="allocation-correction-funding-price">Price</label><input id="allocation-correction-funding-price" type="number" min="0" step="0.0001" class="field" required></div><div><label class="label" for="allocation-correction-funding-fx">FX to GBP</label><input id="allocation-correction-funding-fx" type="number" min="0" step="0.000001" class="field" required></div><div><label class="label" for="allocation-correction-funding-fees">Fees</label><input id="allocation-correction-funding-fees" type="number" min="0" step="0.01" class="field" required></div></div>\n'''
if old not in s: raise SystemExit('correction funding form marker missing')
s = s.replace(old, new, 1)

old = '''            funding_fees:Number(el('allocation-correction-funding-fees').value||0),\n            target_quantity:Number(el('allocation-correction-target-qty').value),\n'''
new = '''            funding_fees:Number(el('allocation-correction-funding-fees').value||0),\n            funding_fx_rate_to_base:Number(el('allocation-correction-funding-fx').value||1),\n            target_quantity:Number(el('allocation-correction-target-qty').value),\n'''
if old not in s: raise SystemExit('correction payload marker missing')
s = s.replace(old, new, 1)

old = '''    function matchCorrectedTargetToFunding() {\n        const proceeds=Number(el('allocation-correction-funding-qty').value||0)*Number(el('allocation-correction-funding-price').value||0)-Number(el('allocation-correction-funding-fees').value||0);\n        const price=Number(el('allocation-correction-target-price').value||0), fx=Number(el('allocation-correction-target-fx').value||1), fees=Number(el('allocation-correction-target-fees').value||0);\n        if(proceeds<=0 || price<=0 || fx<=0) return;\n        const qty=Math.max(0,(proceeds/fx-fees)/price);\n'''
new = '''    function matchCorrectedTargetToFunding() {\n        const fundingLocal=Number(el('allocation-correction-funding-qty').value||0)*Number(el('allocation-correction-funding-price').value||0)-Number(el('allocation-correction-funding-fees').value||0);\n        const fundingFx=Number(el('allocation-correction-funding-fx').value||1);\n        const proceeds=fundingLocal*fundingFx;\n        const price=Number(el('allocation-correction-target-price').value||0), fx=Number(el('allocation-correction-target-fx').value||1), fees=Number(el('allocation-correction-target-fees').value||0);\n        if(proceeds<=0 || fundingFx<=0 || price<=0 || fx<=0) return;\n        const qty=Math.max(0,(proceeds/fx-fees)/price);\n'''
if old not in s: raise SystemExit('correction match marker missing')
s = s.replace(old, new, 1)

old = '''            el('allocation-correction-funding-price').value=Number(fundingData.reference_close).toFixed(4);\n            el('allocation-correction-target-price').value=Number(targetData.reference_close).toFixed(4);\n            el('allocation-correction-target-fx').value=Number(targetData.fx_rate_to_base||1).toFixed(6);\n            const fundingSession=fundingData.used_previous_session?`previous session ${prettyDate(fundingData.price_date)}`:`close ${prettyDate(fundingData.price_date)}`;\n            const targetSession=targetData.used_previous_session?`previous session ${prettyDate(targetData.price_date)}`:`close ${prettyDate(targetData.price_date)}`;\n            const fxSession=targetData.currency==='GBP'?'FX 1.000000':`FX ${Number(targetData.fx_rate_to_base).toFixed(6)} ${targetData.currency}/GBP · ${prettyDate(targetData.fx_price_date)}`;\n            el('allocation-correction-funding-status').textContent=`✓ ${fundingSession}`; el('allocation-correction-funding-status').className='text-[10px] font-black text-emerald-700 mt-1';\n            el('allocation-correction-target-status').textContent=`✓ ${targetSession} · ${fxSession}`; el('allocation-correction-target-status').className='text-[10px] font-black text-emerald-700 mt-1';\n'''
new = '''            el('allocation-correction-funding-price').value=Number(fundingData.reference_close).toFixed(4);\n            el('allocation-correction-funding-fx').value=Number(fundingData.fx_rate_to_base||1).toFixed(6);\n            el('allocation-correction-target-price').value=Number(targetData.reference_close).toFixed(4);\n            el('allocation-correction-target-fx').value=Number(targetData.fx_rate_to_base||1).toFixed(6);\n            const fundingSession=fundingData.used_previous_session?`previous session ${prettyDate(fundingData.price_date)}`:`close ${prettyDate(fundingData.price_date)}`;\n            const targetSession=targetData.used_previous_session?`previous session ${prettyDate(targetData.price_date)}`:`close ${prettyDate(targetData.price_date)}`;\n            const fundingFxSession=fundingData.currency==='GBP'?'FX 1.000000':`FX ${Number(fundingData.fx_rate_to_base).toFixed(6)} ${fundingData.currency}/GBP · ${prettyDate(fundingData.fx_price_date)}`;\n            const fxSession=targetData.currency==='GBP'?'FX 1.000000':`FX ${Number(targetData.fx_rate_to_base).toFixed(6)} ${targetData.currency}/GBP · ${prettyDate(targetData.fx_price_date)}`;\n            el('allocation-correction-funding-status').textContent=`✓ ${fundingSession} · ${fundingFxSession}`; el('allocation-correction-funding-status').className='text-[10px] font-black text-emerald-700 mt-1';\n            el('allocation-correction-target-status').textContent=`✓ ${targetSession} · ${fxSession}`; el('allocation-correction-target-status').className='text-[10px] font-black text-emerald-700 mt-1';\n'''
if old not in s: raise SystemExit('correction market data marker missing')
s = s.replace(old, new, 1)

old = '''        el('allocation-correction-funding-price').value=funding.price;\n        el('allocation-correction-funding-fees').value=funding.fees||0;\n        el('allocation-correction-target-qty').value=target.quantity;\n'''
new = '''        el('allocation-correction-funding-price').value=funding.price;\n        el('allocation-correction-funding-fx').value=funding.fx_rate_to_base||1;\n        el('allocation-correction-funding-fees').value=funding.fees||0;\n        el('allocation-correction-target-qty').value=target.quantity;\n'''
if old not in s: raise SystemExit('correction open marker missing')
s = s.replace(old, new, 1)

old = '''    ['allocation-correction-funding-qty','allocation-correction-funding-price','allocation-correction-funding-fees','allocation-correction-target-qty','allocation-correction-target-price','allocation-correction-target-fx','allocation-correction-target-fees','allocation-correction-reason'].forEach(id=>el(id).addEventListener('input',()=>invalidateAllocationCorrectionPreview()));\n'''
new = '''    ['allocation-correction-funding-qty','allocation-correction-funding-price','allocation-correction-funding-fx','allocation-correction-funding-fees','allocation-correction-target-qty','allocation-correction-target-price','allocation-correction-target-fx','allocation-correction-target-fees','allocation-correction-reason'].forEach(id=>el(id).addEventListener('input',()=>invalidateAllocationCorrectionPreview()));\n'''
if old not in s: raise SystemExit('correction listeners marker missing')
s = s.replace(old, new, 1)

old = '''            if(kind==='funding'){\n                el('allocation-funding-price').value=Number(data.reference_close).toFixed(4);\n                status.textContent=`✓ Verified · ${data.name}${data.exchange?' · '+data.exchange:''} · ${Number(data.held_quantity||0).toLocaleString('en-GB')} units held${previous}`;\n            }else{\n'''
new = '''            if(kind==='funding'){\n                el('allocation-funding-currency').value=data.currency||'GBP';\n                el('allocation-funding-fx').value=Number(data.fx_rate_to_base||1).toFixed(6);\n                el('allocation-funding-price').value=Number(data.reference_close).toFixed(4);\n                const fundingFxInfo=data.currency==='GBP' ? ' · FX 1.000000' : ` · FX ${Number(data.fx_rate_to_base).toFixed(6)} ${data.currency}/GBP${data.fx_used_previous_session?' from '+prettyDate(data.fx_price_date):' on '+prettyDate(data.fx_price_date)}`;\n                status.textContent=`✓ Verified · ${data.name}${data.exchange?' · '+data.exchange:''} · ${data.currency} · ${Number(data.held_quantity||0).toLocaleString('en-GB')} units held${previous}${fundingFxInfo}`;\n            }else{\n'''
if old not in s: raise SystemExit('funding verification marker missing')
s = s.replace(old, new, 1)

old = '''    function updateAllocationPreview() {\n        const fundingQty=Number(el('allocation-funding-qty').value||0), fundingPrice=Number(el('allocation-funding-price').value||0), fundingFees=Number(el('allocation-funding-fees').value||0);\n        const targetQty=Number(el('allocation-target-qty').value||0), targetPrice=Number(el('allocation-target-price').value||0), targetFees=Number(el('allocation-target-fees').value||0), targetFx=Number(el('allocation-target-fx').value||1);\n        if(!fundingQty || fundingPrice<0 || !targetQty || targetPrice<0){ el('allocation-preview').textContent='Enter both legs to preview funding versus purchase cost.'; return; }\n        const proceeds=fundingQty*fundingPrice-fundingFees;\n        const targetLocal=targetQty*targetPrice+targetFees;\n        const targetBase=targetLocal*targetFx;\n        const residual=proceeds-targetBase;\n        el('allocation-preview').textContent=`Funding proceeds: ${money(proceeds,'GBP')} · Target cost: ${money(targetBase,'GBP')} · Net cash impact: ${residual>=0?'+':''}${money(residual,'GBP')}.`;\n    }\n    ['allocation-funding-qty','allocation-funding-price','allocation-funding-fees','allocation-target-qty','allocation-target-price','allocation-target-fees','allocation-target-fx'].forEach(id=>el(id).addEventListener('input',updateAllocationPreview));\n'''
new = '''    function updateAllocationPreview() {\n        const fundingQty=Number(el('allocation-funding-qty').value||0), fundingPrice=Number(el('allocation-funding-price').value||0), fundingFees=Number(el('allocation-funding-fees').value||0), fundingFx=Number(el('allocation-funding-fx').value||1);\n        const targetQty=Number(el('allocation-target-qty').value||0), targetPrice=Number(el('allocation-target-price').value||0), targetFees=Number(el('allocation-target-fees').value||0), targetFx=Number(el('allocation-target-fx').value||1);\n        if(!fundingQty || fundingPrice<0 || fundingFx<=0 || !targetQty || targetPrice<0){ el('allocation-preview').textContent='Enter both legs to preview funding versus purchase cost.'; return; }\n        const fundingLocal=fundingQty*fundingPrice-fundingFees;\n        const proceeds=fundingLocal*fundingFx;\n        const targetLocal=targetQty*targetPrice+targetFees;\n        const targetBase=targetLocal*targetFx;\n        const residual=proceeds-targetBase;\n        const fundingCurrency=el('allocation-funding-currency').value||'GBP';\n        const fundingDetail=fundingCurrency==='GBP'?'':` (${money(fundingLocal,fundingCurrency)} @ ${fundingFx.toFixed(6)})`;\n        el('allocation-preview').textContent=`Funding proceeds: ${money(proceeds,'GBP')}${fundingDetail} · Target cost: ${money(targetBase,'GBP')} · Net cash impact: ${residual>=0?'+':''}${money(residual,'GBP')}.`;\n    }\n    ['allocation-funding-qty','allocation-funding-price','allocation-funding-fees','allocation-funding-fx','allocation-target-qty','allocation-target-price','allocation-target-fees','allocation-target-fx'].forEach(id=>el(id).addEventListener('input',updateAllocationPreview));\n'''
if old not in s: raise SystemExit('allocation preview marker missing')
s = s.replace(old, new, 1)

old = '''            funding_fees:Number(el('allocation-funding-fees').value||0),\n            target_symbol:el('allocation-target-symbol').value.trim().toUpperCase(),\n'''
new = '''            funding_fees:Number(el('allocation-funding-fees').value||0),\n            funding_fx_rate_to_base:Number(el('allocation-funding-fx').value||1),\n            target_symbol:el('allocation-target-symbol').value.trim().toUpperCase(),\n'''
if old not in s: raise SystemExit('allocation payload marker missing')
s = s.replace(old, new, 1)

old = '''            el('allocation-form').reset(); el('allocation-funding-symbol').value='VUAG.L'; el('allocation-funding-fees').value='0'; el('allocation-target-currency').value='GBP'; el('allocation-target-fx').value='1'; el('allocation-target-fees').value='0'; setTodayDefaults(); el('allocation-funding-status').textContent='Enter a ticker to verify.'; el('allocation-funding-status').className='text-[10px] font-bold text-gray-400 mt-1.5'; el('allocation-target-status').textContent='Enter a ticker to verify.'; el('allocation-target-status').className='text-[10px] font-bold text-gray-400 mt-1.5'; updateAllocationPreview();\n'''
new = '''            el('allocation-form').reset(); el('allocation-funding-symbol').value='VUAG.L'; el('allocation-funding-currency').value='GBP'; el('allocation-funding-fx').value='1'; el('allocation-funding-fees').value='0'; el('allocation-target-currency').value='GBP'; el('allocation-target-fx').value='1'; el('allocation-target-fees').value='0'; setTodayDefaults(); el('allocation-funding-status').textContent='Enter a ticker to verify.'; el('allocation-funding-status').className='text-[10px] font-bold text-gray-400 mt-1.5'; el('allocation-target-status').textContent='Enter a ticker to verify.'; el('allocation-target-status').className='text-[10px] font-bold text-gray-400 mt-1.5'; updateAllocationPreview();\n'''
if old not in s: raise SystemExit('allocation reset marker missing')
s = s.replace(old, new, 1)

p.write_text(s, encoding='utf-8')
