from pathlib import Path

p = Path('sethiportfolio.html')
s = p.read_text(encoding='utf-8')

# Add journal modal before closing flex-grow wrapper / feedback section.
needle = '''        <!-- GOT AN IDEA SECTION -->\n'''
modal = '''        <!-- JOURNAL MODAL -->\n        <div id="journal-modal" class="hidden fixed inset-0 z-[100] bg-gray-950/50 backdrop-blur-sm px-4 py-8 overflow-y-auto" role="dialog" aria-modal="true" aria-labelledby="journal-modal-title">\n            <div class="max-w-3xl mx-auto bg-white rounded-2xl shadow-2xl border border-gray-200 overflow-hidden">\n                <div class="flex items-start justify-between gap-4 p-5 md:p-6 border-b border-gray-100">\n                    <div>\n                        <div class="flex flex-wrap items-center gap-2 mb-2">\n                            <span id="journal-modal-date" class="text-[10px] font-black uppercase tracking-wider text-gray-400"></span>\n                            <span id="journal-modal-category" class="text-[10px] font-black uppercase tracking-wider text-amber-700 bg-amber-50 border border-amber-100 rounded-full px-2 py-0.5"></span>\n                        </div>\n                        <h3 id="journal-modal-title" class="text-2xl md:text-3xl font-black tracking-tight text-gray-900"></h3>\n                        <p id="journal-modal-summary" class="text-sm text-gray-500 mt-2 leading-relaxed"></p>\n                    </div>\n                    <button type="button" onclick="closeJournalModal()" class="shrink-0 w-9 h-9 rounded-full border border-gray-200 text-gray-500 hover:bg-gray-50 font-black" aria-label="Close journal entry">×</button>\n                </div>\n                <div class="p-5 md:p-7">\n                    <div class="mb-5 rounded-xl bg-blue-50 border border-blue-100 px-4 py-3 text-xs text-blue-800 leading-relaxed">\n                        Journal entries document the portfolio's reasoning and methodology. Where stated, retrospective notes are clearly distinguished from contemporaneous decisions.\n                    </div>\n                    <div id="journal-modal-body" class="text-sm md:text-[15px] text-gray-700 leading-7 whitespace-pre-line"></div>\n                </div>\n            </div>\n        </div>\n\n''' + needle
if needle not in s:
    raise SystemExit('feedback section needle missing')
s = s.replace(needle, modal, 1)

# Add journal state beside portfolio state.
needle = "    let portfolioData = { dates: [], portfolio: [], sp500: [], nasdaq: [], vwrl: [] };\n"
replacement = needle + "    let journalEntries = [];\n"
if needle not in s:
    raise SystemExit('portfolioData needle missing')
s = s.replace(needle, replacement, 1)

# Replace renderJournal with modal-capable cards and helpers.
start = s.index('    function renderJournal(entries) {')
end = s.index('    function renderTransactions(transactions) {', start)
new_journal = '''    function openJournalModal(entryId) {\n        const entry = journalEntries.find(j => j.id === entryId);\n        if (!entry) return;\n        document.getElementById('journal-modal-date').textContent = prettyDate(entry.effective_date);\n        document.getElementById('journal-modal-category').textContent = entry.category || 'Journal';\n        document.getElementById('journal-modal-title').textContent = entry.title || '';\n        document.getElementById('journal-modal-summary').textContent = entry.summary || '';\n        document.getElementById('journal-modal-body').textContent = entry.body || '';\n        const modal = document.getElementById('journal-modal');\n        modal.classList.remove('hidden');\n        document.body.style.overflow = 'hidden';\n    }\n\n    function closeJournalModal() {\n        document.getElementById('journal-modal').classList.add('hidden');\n        document.body.style.overflow = '';\n    }\n\n    document.addEventListener('keydown', event => { if (event.key === 'Escape') closeJournalModal(); });\n    document.getElementById('journal-modal').addEventListener('click', event => {\n        if (event.target.id === 'journal-modal') closeJournalModal();\n    });\n\n    function renderJournal(entries) {\n        journalEntries = entries || [];\n        document.getElementById('journal-count').textContent = `${journalEntries.length} published note${journalEntries.length === 1 ? '' : 's'}`;\n        document.getElementById('journal-list').innerHTML = journalEntries.length ? journalEntries.map(j => `\n            <article id="journal-${j.id}" class="rounded-xl border border-gray-200 p-4 md:p-5 hover:border-amber-300 transition">\n                <div class="flex flex-wrap items-center gap-2 text-[10px] font-black uppercase tracking-wider"><span class="text-gray-400">${prettyDate(j.effective_date)}</span><span class="text-amber-700 bg-amber-50 border border-amber-100 rounded-full px-2 py-0.5">${j.category || 'Journal'}</span>${j.related_transaction_id ? '<span class="text-blue-700 bg-blue-50 border border-blue-100 rounded-full px-2 py-0.5">Linked decision</span>' : ''}</div>\n                <h4 class="text-lg font-black mt-2">${j.title}</h4><p class="text-sm text-gray-500 mt-1 leading-relaxed">${j.summary || ''}</p>\n                ${j.body ? `<button type="button" onclick="openJournalModal('${j.id}')" class="mt-3 text-xs font-black text-blue-700 hover:text-blue-900">Read analysis →</button>` : ''}\n            </article>`).join('') : '<div class="rounded-xl border border-dashed border-gray-200 p-7 text-sm text-gray-400 text-center">No published investment notes yet. Future portfolio decisions will appear here with their dated rationale.</div>';\n    }\n\n'''
s = s[:start] + new_journal + s[end:]

# Replace transaction renderer so linked transactions expose rationale.
start = s.index('    function renderTransactions(transactions) {')
end = s.index('    let loadingTimer;', start)
new_transactions = '''    function renderTransactions(transactions) {\n        const list = (transactions || []).slice().reverse();\n        const rationaleByTransaction = new Map(journalEntries.filter(j => j.related_transaction_id).map(j => [j.related_transaction_id, j]));\n        document.getElementById('change-log').innerHTML = list.length ? list.map(t => {\n            const instrument = t.instruments || {};\n            const side = String(t.side || '').toUpperCase();\n            const rationale = rationaleByTransaction.get(t.id);\n            return `<div class="p-5 hover:bg-gray-50/60 transition"><div class="flex items-center justify-between gap-3"><div><div class="flex items-center gap-2"><span class="font-black">${instrument.symbol || '—'}</span><span class="text-[10px] uppercase tracking-wider font-black ${side==='BUY'?'text-emerald-700 bg-emerald-50':'text-red-700 bg-red-50'} rounded-full px-2 py-0.5">${side}</span>${rationale ? '<span class="text-[9px] uppercase tracking-wider font-black text-blue-700 bg-blue-50 border border-blue-100 rounded-full px-2 py-0.5">Rationale linked</span>' : ''}</div><p class="text-xs text-gray-500 mt-1">${Number(t.quantity).toLocaleString('en-GB')} units @ ${fmtMoney(Number(t.price), t.currency || instrument.currency || 'GBP')}</p></div><span class="text-xs font-bold text-gray-400">${prettyDate(t.trade_date)}</span></div>${t.note ? `<p class="text-[11px] text-gray-500 mt-3">${t.note}</p>` : ''}${rationale ? `<button type="button" onclick="openJournalModal('${rationale.id}')" class="mt-3 text-xs font-black text-blue-700 hover:text-blue-900">View rationale →</button>` : ''}</div>`;\n        }).join('') : '<div class="p-6 text-sm text-gray-400 text-center">No portfolio transactions recorded.</div>';\n    }\n\n'''
s = s[:start] + new_transactions + s[end:]

p.write_text(s, encoding='utf-8')
print('Patched SethiPortfolio journal experience')
